# Generated by Django 4.2.7 on 2024-12-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-date', '-id'], name='api_transac_date_13feda_idx'),
        ),
    ]
