# Generated by Django 4.2.7 on 2024-12-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_journal_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['-date', '-id'], name='api_checkli_date_f17de9_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['-date', '-id'], name='api_journal_date_ddf538_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-date', '-id'], name='api_task_date_68404d_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['-date', '-id'], name='api_todo_date_38e061_idx'),
        ),
    ]
