# Generated by Django 5.1.4 on 2025-01-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_category_type_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('credit_transfer', 'Credit Transfer'), ('debit_transfer', 'Debit Transfer')], max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('credit_transfer', 'Credit Transfer'), ('debit_transfer', 'Debit Transfer')], max_length=25),
        ),
    ]
