# Generated by Django 5.1.4 on 2025-01-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(default='XXXXXXXXXXXX', max_length=100),
        ),
    ]
