# Generated by Django 5.1.4 on 2025-01-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('savings', 'Savings'), ('slary_account', 'Slary Account'), ('primary_account', 'Primary Account'), ('secondary_account', 'Secondary Account'), ('inhand', 'In Hand')], max_length=50),
        ),
    ]
