# Generated by Django 5.1.4 on 2025-01-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_category_type_alter_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selftransfer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
