# Generated by Django 5.1.4 on 2025-01-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('primary_account', 'Primary Account'), ('secondary_account', 'Secondary Account'), ('savings_account', 'Savings Account')], max_length=50),
        ),
    ]
