# Generated by Django 5.1.4 on 2025-06-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', '-date', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='api_task_date_68404d_idx',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['order', '-date', '-id'], name='api_task_order_7e0195_idx'),
        ),
    ]
