# Generated by Django 5.1.4 on 2025-06-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['type', 'date', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='api_categor_type_28ee42_idx',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['type', 'date', 'id'], name='api_categor_type_d2878b_idx'),
        ),
    ]
